### ISSUE TITLE
Terminal can't install apts

### ISSUE THREAD

**Issue by erenmete** [vhqtvn/VHEditor-Android#106]
I assume the built-in termux is an old version, because this issue was in older versions of it and fixed in the later versions

It is still possible to install them using debs but it's very bothersome to track all the dependancies and install them one by one.

![Screenshot_20220201-233652_VHEditor](https://user-images.githubusercontent.com/58091473/152047176-72a768a8-d088-4ae8-986e-35355bea1aed.png)
![Screenshot_20220201-233659_VHEditor](https://user-images.githubusercontent.com/58091473/152047161-01977c73-efba-4b7f-840f-78b4bbfae122.png)

**Comment by vhqtvn** [comment]
That 401 problem should be fixed in latest version, but you need to reset rootfs first. Reopen the issue if problem still there.

**Comment by shanyan-wcx** [comment]
> 

how to reset rootfs ?

**Comment by vhqtvn** [comment]
Use the cogs icon in main screen.
