### ISSUE TITLE
Termux code-server

### ISSUE THREAD

**Issue by wioenena-q** [vhqtvn/VHEditor-Android#107]
It would be nice if we could connect to the code server that we will start via Termux from the application.

**Comment by vhqtvn** [comment]
Hm i dont understand your point?

**Comment by wioenena-q** [comment]
code-server would be in recent versions.

**Comment by wioenena-q** [comment]
code-server would be in recent versions.

**Comment by Belajar777** [comment]
https://github.com/vhqtvn/VHEditor-Android/issues/107#issuecomment-1037245639
