### ISSUE TITLE
apt & pkg issue

### ISSUE THREAD

**Issue by shanyan-wcx** [vhqtvn/VHEditor-Android#109]
When I run apt updete or pkg update, it show "You might want to run 'apt --fix-broken install'", and I can't install any thing. If I run this code, I can't use pkg because "curl : Depends : libcurl (= 7.77.0~3) but 7.78.0 is installed".

**Comment by shanyan-wcx** [comment]
I can't even open the editor again.

**Comment by shanyan-wcx** [comment]
![屏幕截图 2022-02-03 115835](https://user-images.githubusercontent.com/58252651/152278955-2cc08273-b6e6-4ea9-8974-a6b50f54d07b.png)
![Screenshot_20220203_114958](https://user-images.githubusercontent.com/58252651/152278960-97ee07be-52f0-43bc-be18-7a9dbdb8e0b6.jpg)

**Comment by shanyan-wcx** [comment]
This problem makes the app unusable. Please fix it as soon as possible.

**Comment by vhqtvn** [comment]
Are you using the latest version? Have you reset rootfs?

**Comment by shanyan-wcx** [comment]
> Are you using the latest version? Have you reset rootfs?

Yes, I have

**Comment by shanyan-wcx** [comment]
It's no use even uninstalling and then reinstalling

**Comment by brainer3220** [comment]
I think related storage access issue. #43

**Comment by shanyan-wcx** [comment]
> I think related storage access issue. #43

Do you have a solution?

**Comment by brainer3220** [comment]
> > I think related storage access issue. #43
> 
> Do you have a solution?

In the Termux Github have [TermuxFileUtils](https://github.com/termux/termux-app/blob/85376e2796c7d85a5866914f6b9e19120dfdbd8f/termux-shared/src/main/java/com/termux/shared/termux/file/TermuxFileUtils.java#L25) class.

Probably update [TermuxInstaller.java ](https://github.com/vhqtvn/VHEditor-Android/blob/3c1ddaabdadac1d6837c8e5ccf42792d2126958e/app/src/main/java/com/termux/app/TermuxInstaller.java) and related files, it's working.

**Comment by shanyan-wcx** [comment]
> > > I think related storage access issue. #43
> > 
> > 
> > Do you have a solution?
> 
> In the Termux Github have [TermuxFileUtils](https://github.com/termux/termux-app/blob/85376e2796c7d85a5866914f6b9e19120dfdbd8f/termux-shared/src/main/java/com/termux/shared/termux/file/TermuxFileUtils.java#L25) class.
> 
> Probably update [TermuxInstaller.java ](https://github.com/vhqtvn/VHEditor-Android/blob/3c1ddaabdadac1d6837c8e5ccf42792d2126958e/app/src/main/java/com/termux/app/TermuxInstaller.java) and related files, it's working.

I don't quite understand. Can you be more specific?

**Comment by shanyan-wcx** [comment]
> > > > > I think related storage access issue. #43
> > > > 
> > > > 
> > > > Do you have a solution?
> > > 
> > > 
> > > In the Termux Github have [TermuxFileUtils](https://github.com/termux/termux-app/blob/85376e2796c7d85a5866914f6b9e19120dfdbd8f/termux-shared/src/main/java/com/termux/shared/termux/file/TermuxFileUtils.java#L25) class.
> > > Probably update [TermuxInstaller.java ](https://github.com/vhqtvn/VHEditor-Android/blob/3c1ddaabdadac1d6837c8e5ccf42792d2126958e/app/src/main/java/com/termux/app/TermuxInstaller.java) and related files, it's working.
> > 
> > 
> > I don't quite understand. Can you be more specific?
> 
> [‎VHEditor‎](https://github.com/vhqtvn/VHEditor-Android)‎基于‎[‎Termux‎](https://github.com/termux/termux-app)‎。‎

I know that. I just don't know how to update termuxinstaller.java and related files

**Comment by TheOG00** [comment]
i can't install thos too
https://mega.nz/file/95NGmBwD#F9nxYje_XyNuR2315O1QE2h7Nhhig0f6jzmsh_NVBxI

**Comment by wilgnne** [comment]
> ![屏幕截图 2022-02-03 115835](https://user-images.githubusercontent.com/58252651/152278955-2cc08273-b6e6-4ea9-8974-a6b50f54d07b.png) ![Screenshot_20220203_114958](https://user-images.githubusercontent.com/58252651/152278960-97ee07be-52f0-43bc-be18-7a9dbdb8e0b6.jpg)

As described in the error, run

`apt --fix-broken install`

**Comment by wilgnne** [comment]
`apt --fix-broken install` worked for me, app version 1.6.0, server version 3.12.0

**Comment by vhqtvn** [comment]
Please try the latest version.
