### ISSUE TITLE
Error on use pkg install nodejs

### ISSUE THREAD

**Issue by kaderisoft** [vhqtvn/VHEditor-Android#110]
![Screenshot_٢٠٢٢٠٢٠٣-١٥٢٦٠٠_VHEditor.jpg](https://user-images.githubusercontent.com/4380138/152342676-b2cd3439-e1f3-443d-be37-bdb12be53aeb.jpg)

V1.6.0

**Comment by Juhan280** [comment]
I am also getting this same error

**Comment by EngSalamaNaief** [comment]
i have the same problem and i can't install git also

**Comment by vhqtvn** [comment]
![IMG_20220219_173516_193.jpg](https://user-images.githubusercontent.com/8930337/154797294-a0f6b61e-f102-4ce0-8cad-ffc5c3f09c7d.jpg)

just run `apt -fix-broken install`

**Comment by EngSalamaNaief** [comment]
> ![IMG_20220219_173516_193.jpg](https://user-images.githubusercontent.com/8930337/154797294-a0f6b61e-f102-4ce0-8cad-ffc5c3f09c7d.jpg)
> 
> just run `apt -fix-broken install`

when i do that and stop server can't start again
![Uploading Screenshot_٢٠٢٢-٠٢-١٩-١٢-٤٣-٢٨-٢٦٣_vn.vhn.vsc.jpg…]()

**Comment by shanyan-wcx** [comment]
> ![IMG_20220219_173516_193.jpg](https://user-images.githubusercontent.com/8930337/154797294-a0f6b61e-f102-4ce0-8cad-ffc5c3f09c7d.jpg)
> 
> just run `apt --fix-broken install`

This will delete many things and make it impossible to start after stopping the server.

**Comment by vhqtvn** [comment]
I'm rebuilding repository, should take some days.

**Comment by HantonSacu** [comment]
would install git work on some previous version?

**Comment by vhqtvn** [comment]
Please try the latest version.

**Comment by JsKarimi** [comment]
No solution was found for this problem
