### ISSUE TITLE
I can't install any extensions.

### ISSUE THREAD

**Issue by Isai-dc** [vhqtvn/VHEditor-Android#112]
For the extensions  I want to install I get the message:

 _"Can't install 'extension_name' extension because it is not compatible with the current version of VS Code (version 1.60.0)."_ 

I'm running App version: 1.6.0 & Server version: 3.12.0

**Comment by brainer3220** [comment]
Duplicate https://github.com/vhqtvn/VHEditor-Android/issues/109

**Comment by vhqtvn** [comment]
Should be working in latest version.
