### ISSUE TITLE
VSCode server not running

### ISSUE THREAD

**Issue by BBlack-monkey** [vhqtvn/VHEditor-Android#113]
**Can someone tell me why the server isnt running...
When i tap start editor it say starting after a while it says vscode server not running why?**

**Comment by HantonSacu** [comment]
Have you seen trace in terminal when you start?
If you could screenshot that could help maybe.

**Comment by vhqtvn** [comment]
Please provide more information, maybe your device has some strict blocking on running binaries.

**Comment by BBlack-monkey** [comment]
At last after getting many advises now it is working
