### ISSUE TITLE
Downloading Issue

### ISSUE THREAD

**Issue by Kalmai221** [vhqtvn/VHEditor-Android#115]
Everything I tried downloading, It kept on showing "App Not Installed"

Android 10
Oppo A15

**Comment by Kunle550** [comment]
After downloading,it tells me authorization needed in the notification bar and then i won't be able to find the file I downloaded,any help on that?

**Comment by vhqtvn** [comment]
Hi, downloads are provided by github, there should be no problem (just tried). Please reopen if problem still occurs.
