### ISSUE TITLE
Crash after clicking install server

### ISSUE THREAD

**Issue by shanyan-wcx** [vhqtvn/VHEditor-Android#117]
I installed 1.70 and reset rootfs. Then I clicked install server and crashed.

**Comment by Muulsh** [comment]
I have the same issue on Android 11/ miui 12.5
i downgraded the app to 1.6.0 and it works fine now

**Comment by laser-brain** [comment]
Same problem. APK size seems to be suspiciously small - 32M compared to 100M+ on earlier versions

**Comment by Craft374** [comment]
I have the same problem
I hope it gets updated soon

**Comment by vhqtvn** [comment]
Check https://github.com/vhqtvn/VHEditor-Android/releases/tag/v1.7.1

**Comment by laser-brain** [comment]
Still crashing with Version 1.7.1 on Lenovo P11 Tablet (Android 11)
