### ISSUE TITLE
There are still problems with apt upgrade, apt install is OK.

### ISSUE THREAD

**Issue by shanyan-wcx** [vhqtvn/VHEditor-Android#118]

**Comment by vhqtvn** [comment]
Please run `apt update` first, or just reset root fs again, i've cleanup the whole repository.

**Comment by vhqtvn** [comment]
Seems that new apt after upgrading cannot run due to missing of libzstd, somehow dependencies broken

You'll need to install zstd yourself to make it work again:

```
curl -L https://vsc.vhn.vn/termux-packages-24/debs/0c8fbb7a69f0215f745e00afee3cda455c67b411/all/zstd_1.5.2_aarch64.deb --output zstd_1.5.2_aarch64.deb
dpkg --install zstd_1.5.2_aarch64.deb
```
