### ISSUE TITLE
Unable to locate pakage

### ISSUE THREAD

**Issue by VaibhavWebDev** [vhqtvn/VHEditor-Android#119]
Bro, the new version is the best but only there is one issue that in terminal it just says unable to locate pakage. I tried by changing the repo too but it says that only. What should I do pls tell..

**Comment by vhqtvn** [comment]
Please take screenshot of the error.

**Comment by VaibhavWebDev** [comment]
![Screenshot_2022-03-29-15-17-44-811.jpeg](https://user-images.githubusercontent.com/98445968/160584896-700f4ced-a274-4551-b9ce-b25ceba3f05f.jpeg)

**Comment by vhqtvn** [comment]
My ssl certificate expired, renewed now.

**Comment by VaibhavWebDev** [comment]
> My ssl certificate expired, renewed now.

Bro so will this issue be solved?

**Comment by vhqtvn** [comment]
Just try again if it's resolved now.

**Comment by VaibhavWebDev** [comment]
> Just try again if it's resolved now.

New error is there bro that wait I'll send screenshot

**Comment by VaibhavWebDev** [comment]
> > Just try again if it's resolved now.
> 
> New error is there bro that wait I'll send screenshot

![Screenshot_2022-03-29-16-19-04-291.jpeg](https://user-images.githubusercontent.com/98445968/160595774-022d2eac-95ce-40aa-98ce-2cb6d1abc9f3.jpeg)

**Comment by VaibhavWebDev** [comment]
![Screenshot_2022-03-29-15-17-44-811.jpeg](https://user-images.githubusercontent.com/98445968/160584896-700f4ced-a274-4551-b9ce-b25ceba3f05f.jpeg) @vhqtvn
