### ISSUE TITLE
unable to install python & even not able to upgrade  with apt

### ISSUE THREAD

**Issue by normal1234** [vhqtvn/VHEditor-Android#124]
heres a screenshot please have a llook and give solution.
![Uploading Screenshot_20220403-113243_VHEditor.jpg…]()

**Comment by normal1234** [comment]
![Screenshot_20220403-113243_VHEditor](https://user-images.githubusercontent.com/101281485/161414341-65da91f0-745b-4779-a930-9cce038851bd.jpg)

**Comment by vhqtvn** [comment]
Try `apt install curl=7.81.0 libcurl=7.81.0`
