### ISSUE TITLE
Existing termux installation

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [vhqtvn/VHEditor-Android#125]
Heya, this looks neat but I'm wondering if i can use my existing termux installation with this?

**Comment by vhqtvn** [comment]
I think you can install and run code-server inside your termux and use it as remote server on this editor.

Or download my custom package on https://github.com/vhqtvn/vscode-android-server, extract on your termux installation to run the server. I have some patches within kotlin code so you may have to do them yourself.

**Comment by Mythical-Forest-Collective** [comment]
Thanks!
