### ISSUE TITLE
There are many problems in version 1.8.1

### ISSUE THREAD

**Issue by shanyan-wcx** [vhqtvn/VHEditor-Android#126]
No extensions can be found. The language pack installed from the file does not take effect. The page layout cannot be saved. It will change back to the default layout when it is opened next time.

**Comment by vhqtvn** [comment]
Yes, but nothing logged in the console, strange. I'll check it soon.

**Comment by vhqtvn** [comment]
I fixed the extensions problem. Seems that vscode or code-server default to no extensions gallery, i added open-vsx gallery if the server not configured. Check the new js code in boot.sh (https://github.com/vhqtvn/VHEditor-Android/commit/2c4f4c21506dd0673e10b3e2e22b994296feb88e) for gallery configuration.

Language packs seems not to be installable in current OSS version.

About layout problem, I cannot reproduce.

**Comment by shanyan-wcx** [comment]
I still can't find any extensions. I don't understand how the problem is solved.
In addition, the following video is the layout problem:

https://user-images.githubusercontent.com/58252651/167263556-84b8db34-fcd7-47b4-92b7-3dd10dab24e0.mp4

**Comment by vhqtvn** [comment]
Sorry a typo in the fix, check the extension problem again when 1.8.3 is built.

**Comment by vhqtvn** [comment]
Yes layout parameters like width of sidebar is reset, but things like editor split and width/height of individual editor is kept event after server restart. There maybe some changes in code-server's related logics.

**Comment by vhqtvn** [comment]
@shanyan-wcx extensions working now right?

**Comment by shanyan-wcx** [comment]
> @shanyan-wcx extensions working now right?

It works
