### ISSUE TITLE
Code-OSS has poor support for extensions. 

### ISSUE THREAD

**Issue by shanyan-wcx** [vhqtvn/VHEditor-Android#127]
Code-OSS has poor support for extensions. Why not use the arm version of vscode? In addition, the extension and settings will be lost after each update. It is troublesome to reconfigure. Can you save the configuration and extensions?

**Comment by vhqtvn** [comment]
Because VSCode is built on Electron and Electron doesnt support Android.

I'll check about plugin stuff later, but settings are saved on $HOME so it will persists, except you reset rootfs, but in later version reset rootfs will leave $HOME untouched.
