### ISSUE TITLE
When I run c++ code, it has permission denial, which will not occur in other languages.

### ISSUE THREAD

**Issue by shanyan-wcx** [vhqtvn/VHEditor-Android#128]
![微信图片_20220510190037](https://user-images.githubusercontent.com/58252651/167614568-5031909d-b641-4169-8f07-41841705390b.jpg)

**Comment by VarunNalagandla** [comment]
Yes not coming code runner

**Comment by LiznYang** [comment]
Try running under /home/

**Comment by LiznYang** [comment]
> Try running under /home/
<img width="430" alt="截屏2022-07-10 08 19 19" src="https://user-images.githubusercontent.com/47726910/178126686-263efec7-5d85-4d58-8d24-0fe1f9f009cb.png">

**Comment by vhqtvn** [comment]
`home/storage` is symlink-ed to external storage, which Android does not enable execution bit for security, so executables wont work, try to use a folder outside `storage` it will work.
