### ISSUE TITLE
create-react-app, nodemon do not work

### ISSUE THREAD

**Issue by Heavens-knt** [vhqtvn/VHEditor-Android#130]
When trying to create a REACT APP by using CREATE-REACT-APP command, the error message below appears:' ' bash: /data/data/vn.vsh.vsc/files/bin/create-react-app: usr/bin/env: bad interpreter: no such file or directory '', the same error occurred when trying use NODEMON for my NodeJs App:  '' bash: /data/data/vn.vsh.vsc/files/bin/nodemon: usr/bin/env: bad interpreter: no such file or directory ''
![Screenshot_2022-05-17-10-40-52-29_9c1589490c906a9623165cad7a860a58](https://user-images.githubusercontent.com/83799312/168769294-e94382a7-f2a1-4b7d-b80d-7a88faaa24b6.jpg)
![Uploading Screenshot_2022-05-17-10-38-52-29_9c1589490c906a9623165cad7a860a58.jpg…]()

**Comment by vhqtvn** [comment]
Edit "create-react-app" file and remove `/usr/bin/env` from shebang.
