### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by Ahmadreza-1995** [vhqtvn/VHEditor-Android#139]
stop or kill editor session= reset all settings :(

**Comment by gregjuice** [comment]
`https://bit.ly/3ayvKdtAndroid`

**Comment by Ahmadreza-1995** [comment]
> `https://bit.ly/3ayvKdtAndroid`

Something's wrong here.!!!

**Comment by vhqtvn** [comment]
Which settings are your referring?

**Comment by gregjuice** [comment]
Everything

**Comment by Ahmadreza-1995** [comment]
> Everything 

exactly

**Comment by gregjuice** [comment]
> > Everything 
> 
> exactly

[So what do we do ?? 😭😭

**Comment by Ahmadreza-1995** [comment]
> The new version fixed this problem.

Thanks dear❤️

**Comment by anonimo82** [comment]
The problem arisen again

**Comment by anonimo82** [comment]
@vhqtvn 
Every time I open the editor, I have to adjust settings in the "Get started" page.
