### ISSUE TITLE
the editor does not work

### ISSUE THREAD

**Issue by MarkD635** [vhqtvn/VHEditor-Android#148]
When I start the editor the application turns black and then closes 
App versión: 2.1.0 arm
Device: Samsung A10S

**Comment by vhqtvn** [comment]
If you can use adb please check the crash with logcat, else maybe i'll need to add some crash logger in latter version.

**Comment by vhqtvn** [comment]
Samsung A10S use Mediatek MT6762 Helio P22 is 64bit device, please download arm64 version.

**Comment by MarkD635** [comment]
I have tried, but I get the error that the apk can not be installed

**Comment by vhqtvn** [comment]
Hm arm apk can be installed but not arm64?

**Comment by MarkD635** [comment]
Yes
