### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Raffa064** [vhqtvn/VHEditor-Android#156]
You will add support to the incompatible plugins? I'm wanting to use "Code snap".

**Comment by vhqtvn** [comment]
There're several factors for "incompatible" plugins:
- code-server
- android
- termux

Any of them may require works/patches from the plugin side (change to alternative compatible code flows) or one or any number of combination of above.
- Changes to the plugin require maintain the patches for that plugin, and a way to manage/apply new patches as plugin update.
- Change to above elements may affect (break) other stuffs like default features or other plugins feature, so patch much be reviewed very carefully for stability, or the patch must be simple enough to be able to consider bug-free, like touch2pointer or key code hacks within the app.

So, time needed for incompatible plugins is not predictable, I also do not have a design to manage these plugins within VHEditor now. I'll think about this, but it should be better to have support from community.

**Comment by Raffa064** [comment]
Got it... I'd love to contribute but I don't know kotlin and I don't have the tools for it

**Comment by Raffa064** [comment]
Got it... I'd love to contribute but I don't know kotlin and I don't have the tools for it
