### ISSUE TITLE
Sof keyboard 

### ISSUE THREAD

**Issue by Raffa064** [vhqtvn/VHEditor-Android#158]
How to open sof keyboard ??
Some previous versions it opened all the time for nothing... and now it never opens
I have a physical keyboard but other users may not have them... I recommend you put an open button or even a key combination or gestures

**Comment by vhqtvn** [comment]
Hm it should be no problem in the latest release, it should be relating to your installed keyboard instead.

**Comment by Raffa064** [comment]
my keyboard is the gboard... the android's native keyboard.

**Comment by vhqtvn** [comment]
Maybe gboard detect the physical keyboard and hide?
