### ISSUE TITLE
Problem before 2.4

### ISSUE THREAD

**Issue by Raffa064** [vhqtvn/VHEditor-Android#163]
From approximately version 2.4 there was a performance drop that is crashing and the mouse gets all blurry and crooked when moved

Exemple with hardware acellerated:
https://user-images.githubusercontent.com/74153113/180035309-68b58e13-96a7-4009-8792-a122caebdd4b.mp4

Example without hardware acellerated:
https://user-images.githubusercontent.com/74153113/180036041-43851de7-cb85-4733-a360-8b2a4ea6fb5b.mp4

Apparently the fps is getting low out of nowhere... And this acellerated hardware sometimes helps, sometimes it gets in the way... but it's pretty unstable

**Comment by vhqtvn** [comment]
Thanks for detailed report.

https://github.com/vhqtvn/VHEditor-Android/compare/v2.3.0...v2.4.0#diff-345eca699b1314e7c1aba294035698cf66644a5111586c256b60348f35ed5e89R38

HW Accelerated settings is applied to the webview only, the mouse layer always use hw accelerated starting from v2.4, maybe i'll add a setting for the mouse layer.

**Comment by ElvEvosoftOlav** [comment]
@Raffa064 what mouse software are you using?, looks interesting to try :)

**Comment by Raffa064** [comment]
@ElvEvosoftOlav it are a feature of the VHEditor bro, anable it in options
