### ISSUE TITLE
Extension probleme

### ISSUE THREAD

**Issue by MuhammadHasan246** [vhqtvn/VHEditor-Android#166]
Extension is not working and it gives me an error.

**Comment by vhqtvn** [comment]
Which extension?

**Comment by MuhammadHasan246** [comment]
The extension probleme has been solved and the app was downloaded from Playstore. In the previous version 1.3.0, all extensions was available, but in this latest version 2.7.1, very few extensions is available.

**Comment by MuhammadHasan246** [comment]
The extension probleme has been solved.I was downloaded the application from
Playstore. In the previous version 1.3.0, all extensions was available, but
in this latest version 2.7.1, very few extensions is available.
