### ISSUE TITLE
Editor Terminal

### ISSUE THREAD

**Issue by Ahmadreza-1995** [vhqtvn/VHEditor-Android#168]
built-in terminal in editor not show anything![Screenshot_20220723_102446_vn.vhn.vsc.jpg](https://user-images.githubusercontent.com/99149420/180592623-e7fbaedc-8787-4a74-aaec-fcea1a4e2f0e.jpg)

**Comment by vhqtvn** [comment]
Change VSCode's setting "Terminal > Integrated > Gpu Acceleration" to `off` or `canvas`.
