### ISSUE TITLE
ERROR EDITING JAVASCRIPT FILES

### ISSUE THREAD

**Issue by fera765** [vhqtvn/VHEditor-Android#17]
error when editing javascript files within a ReactJS project

**Comment by vhqtvn** [comment]
What's the error? Please provide screenshot.

**Comment by fera765** [comment]
Video

**Comment by fera765** [comment]
https://easyupload.io/ti85jo

**Comment by fera765** [comment]
There is the video with the bug

**Comment by vhqtvn** [comment]
Thank you for reporting, i'll fix it soon.

**Comment by vhqtvn** [comment]
Hi @fera765 what's the keyboard are you using? I cant reproduce the issue using Hacker Keyboard and LG Keyboard.

**Comment by fera765** [comment]
Hacker Keyboard , Probably be bug as test with some extension like eslint, prettier

**Comment by vhqtvn** [comment]
Hi can you please share me your configurations? I really cant replay the bug.
