### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by Raffa064** [vhqtvn/VHEditor-Android#170]
My phone have api 29, but even so this message appears sometimes, it usually disappears when updating but it is not correct

![Screenshot_2022-07-25-17-40-15-245_vn.vhn.vsc.jpg](https://user-images.githubusercontent.com/74153113/180870347-072a0c0c-8e4a-4aa4-aaab-f38f3ddd2708.jpg)

**Comment by vhqtvn** [comment]
Hmm you're using gogple play version?

**Comment by vhqtvn** [comment]
Maybe you auto updated the app from google play, just download latest version from github and install (overwrite).
