### ISSUE TITLE
slow application

### ISSUE THREAD

**Issue by 1999ali1999** [vhqtvn/VHEditor-Android#177]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by 1999ali1999** [comment]
In previous versions it was fast. Now it's slow please solve the problem

**Comment by vhqtvn** [comment]
Which part is slow?

**Comment by vhqtvn** [comment]
Looks like spam.
