### ISSUE TITLE
Unable to change settings

### ISSUE THREAD

**Issue by eldritchgreene** [vhqtvn/VHEditor-Android#18]
The pull down menus in the settings do not open/ don't respond to touchscreen so I'm unable to change settings, any way to fix this?

**Comment by vhqtvn** [comment]
![Screenshot_20200714-130501.png](https://user-images.githubusercontent.com/8930337/87390264-7ea86780-c576-11ea-9682-96f58aead828.png) I can open it here.What's your device model?

**Comment by eldritchgreene** [comment]
I can open normal menus fine too, I meant the drop downs within the settings page. I have since managed to change my settings.json file but would be nice to be able to do it from the settings.
![Screenshot_20200714-111000_2](https://user-images.githubusercontent.com/37325367/87450265-e8029780-c5c3-11ea-981c-0d6932127833.jpg)
Otherwise app works great for me so far thank you!

**Comment by vhqtvn** [comment]
Oh that setting menu is touch-disabled in vscode server's code, i have to add workaround to forward touch event to mouse event and that worked on my devices:
https://github.com/vhqtvn/VHSCode-Android/blob/master/app/src/main/java/vn/vhn/vhscode/CodeServerService.kt#L309
Cosmo is an awesome device but it's extremely hard for me to have access to one, that UI is only pure HTML Dom, can you please try if you can find a workaround for your case?

**Comment by vhqtvn** [comment]
Actually i updated the workaround, please wait and try 1.1.09 to see if the problem is fixed.

**Comment by eldritchgreene** [comment]
OK thanks so much!

**Comment by vhqtvn** [comment]
Hi is it fixed now?

**Comment by eldritchgreene** [comment]
It's fixed :) thanks again.
