### ISSUE TITLE
The $PREFIX and $HOME path is not same as termux

### ISSUE THREAD

**Issue by fingthinking** [vhqtvn/VHEditor-Android#19]
Due to the path setting problem of $prefix and $home, there will be some unexpected permission problems when installing ohmyzsh.

**Comment by vhqtvn** [comment]
I can install ohmyzsh successfully using their git (not oh-my-termux), there're some permissions problems though on completion paths as in this issue https://github.com/ohmyzsh/ohmyzsh/issues/6835 but you can fix that just as in that thread:
```
ZSH_DISABLE_COMPFIX=true
```

**Comment by fingthinking** [comment]
I agree with you, but $HOME is set to Android "/data/vn.vhn.vsc/files". Bug after installing golang, the file directory will be set in "$HOME/go" by default, while "Android/data/ vn.vhn.vsc/files". The file permission in 660 does not have execute permission, so the program in "$HOME/go/bin" cannot run well.

**Comment by vhqtvn** [comment]
Got it, external storage is not mounted as executable, maybe HOME should be mounted to internal data path again.

**Comment by fingthinking** [comment]
Thank U. Looking forward to new version!

**Comment by fingthinking** [comment]
I think, VHEditor could create some soft link like "storage" point to external storage root path.
