### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by MulqiGaming64** [vhqtvn/VHEditor-Android#194]
when I open a terminal in vscode there is no text that I can see, even though I try to run the command, it runs but it doesn't show up.

**Comment by Allhag** [comment]
[``]([url](url))

**Comment by sdproyi** [comment]
![Uploading Screenshot_20220922_135431.jpg…]()

**Comment by sdproyi** [comment]
![Screenshot_20220922_135431](https://user-images.githubusercontent.com/71813700/191741222-6c8603ef-f262-4f57-a499-fe08e1172293.jpg)

**Comment by SowmiyanS** [comment]
This issue is closed already

Change Terminal > Integrated > Gpu Acceleration preference of VSCode to off

[Cannot see letters on terminal #196](https://github.com/vhqtvn/VHEditor-Android/issues/196)
