### ISSUE TITLE
Cannot see letters on terminal

### ISSUE THREAD

**Issue by SowmiyanS** [vhqtvn/VHEditor-Android#196]
When I open a new terminal, I cannot see the output of any command I enter.
I think the color of the output characters are same as the background color of the terminal itself.

**Comment by TheWalruzz** [comment]
What worked for me was to change the theme to a different one and then back to the old one

**Comment by ezra-1** [comment]
It's not working

**Comment by MillironX** [comment]
> What worked for me was to change the theme to a different one and then back to the old one

That doesn't work on either of my machines

**Comment by vhqtvn** [comment]
Please show some screenshots.

**Comment by ezra-1** [comment]
![191741222-6c8603ef-f262-4f57-a499-fe08e1172293.jpg](https://user-images.githubusercontent.com/114309673/194716757-3ee9f8bd-3680-479f-9a05-1127173850d7.jpg)

**Comment by vhqtvn** [comment]
Change `Terminal > Integrated > Gpu Acceleration` preference of VSCode to `off`, I think that will fix the problem.

**Comment by Arbazpatni** [comment]
Yes, it works!
![Screenshot_2022_1009_104836](https://user-images.githubusercontent.com/107135074/194739414-4ab0d88c-51c9-483f-ab34-060ce14802af.jpg)
I changed this in the settings.
