### ISSUE TITLE
[question] - How did you implement hardware keyboard mode?

### ISSUE THREAD

**Issue by anonimo82** [vhqtvn/VHEditor-Android#197]
Hello everyone.
I'd like to have your hardware keyboard mode in "vanilla" Code Server for Termux, and I asked for it here: [Hardware keyboard mode](https://github.com/coder/code-server/discussions/5617), but the developer have no clue on what am I talking about.
Please, can you help me?

Thanks for any help.

**Comment by vhqtvn** [comment]
That mode can not be implemented from code-server.

It works by disable focus to the webview so the current Android's Activity will receive all key events, and then the activity will forward these events to the webview, that prevent imes from working.

**Comment by anonimo82** [comment]
Thanks so much for your reply.
Ok, I'll live with that ... so sad ...
