### ISSUE TITLE
Connecting to remote does not work

### ISSUE THREAD

**Issue by flleeppyy** [vhqtvn/VHEditor-Android#209]
Hiya, I'm having some issues opening a remote editor. I'm running code-server in proot in termux, and i can access it in my web browser, but I can't access it through VHEditor's remote server feature. It just gets stuck at the loading screen.
![Screenshot_20221114-083833_VHEditor.jpg](https://user-images.githubusercontent.com/18307183/201717670-76698acc-afe3-4516-a9a7-c8885014cc01.jpg)
![Screenshot_20221114-083845_Termux.jpg](https://user-images.githubusercontent.com/18307183/201717288-3641ef14-4588-42d5-8fb5-71c35e1a19a5.jpg)
![Screenshot_20221114-083823_VHEditor.jpg](https://user-images.githubusercontent.com/18307183/201717792-b2baa092-9390-45b9-81fb-b03c8b53e221.jpg)

**Comment by vhqtvn** [comment]
Could you be able to load code-server from your browser?

**Comment by flleeppyy** [comment]
Yes

**Comment by canadiannomad** [comment]
I've been trying the same thing, though I have code-server's `cert: true` .. so it has an unsigned localhost cert.. https://localhost:8443 ... Same results, grey screen with cursor, refresh button, and configs at the bottom.
