### ISSUE TITLE
Mouse does not confine to the viewport 

### ISSUE THREAD

**Issue by flleeppyy** [vhqtvn/VHEditor-Android#215]
You're able to move the mouse outside the current view port, and it's possible to lose the mouse. I'm on version 2.12.1 on my Samsung Note 8, Android 9

only way to mitigate it is to bring up the function menu and disable and enable the virtual mouse.

**Comment by Sanberkaygun** [comment]
bro ım use s7+ tablet and ı see my screen two mouse how can ı disable virtual mouse
