### ISSUE TITLE
Can't install packges with apt/pkg

### ISSUE THREAD

**Issue by nanakoTakashi** [vhqtvn/VHEditor-Android#224]
When i install package using apt or pkg get me error
Vhe version:  2.12.1
Code-server version:  4.8.3-cs-2022.11.12-r1
My device: Xiomi Redmi 9T / M2010J19SG 
Android version: 11 
The error: 
unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package clang.
Preparing to unpack .../07-clang_15.0.7_aarch64.deb ...
Unpacking clang (15.0.7) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/07-clang_15.0.7_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package gdbm.
Preparing to unpack .../08-gdbm_1.23_aarch64.deb ...
Unpacking gdbm (1.23) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/08-gdbm_1.23_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package glib.
Preparing to unpack .../09-glib_2.74.5_aarch64.deb ...
Unpacking glib (2.74.5) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/09-glib_2.74.5_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
dpkg (subprocess): unable to execute new glib package post-removal script (/data/data/vn.vhn.vsc/files/usr/var/lib/dpkg/tmp.ci/postrm): Permission denied
dpkg: error while cleaning up:
 new glib package post-removal script subprocess returned error exit status 2
Selecting previously unselected package libandroid-posix-semaphore.
Preparing to unpack .../10-libandroid-posix-semaphore_0.1-3_aarch64.deb ...
Unpacking libandroid-posix-semaphore (0.1-3) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/10-libandroid-posix-semaphore_0.1-3_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
Selecting previously unselected package libcrypt.
Preparing to unpack .../11-libcrypt_0.2-5_aarch64.deb ...
Unpacking libcrypt (0.2-5) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/11-libcrypt_0.2-5_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
Selecting previously unselected package make.
Preparing to unpack .../12-make_4.4_aarch64.deb ...
Unpacking make (4.4) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/12-make_4.4_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package ncurses-ui-libs.
Preparing to unpack .../13-ncurses-ui-libs_6.4-1_aarch64.deb ...
Unpacking ncurses-ui-libs (6.4-1) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/13-ncurses-ui-libs_6.4-1_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
Selecting previously unselected package pkg-config.
Preparing to unpack .../14-pkg-config_0.29.2-2_aarch64.deb ...
Unpacking pkg-config (0.29.2-2) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/14-pkg-config_0.29.2-2_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
Selecting previously unselected package python.
Preparing to unpack .../15-python_3.11.1-2_aarch64.deb ...

**Comment by nanakoTakashi** [comment]
Unpacking python (3.11.1-2) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/15-python_3.11.1-2_aarch64.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package python-pip.
Preparing to unpack .../16-python-pip_22.3.1-3_all.deb ...
Unpacking python-pip (22.3.1-3) ...
dpkg: error processing archive /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/16-python-pip_22.3.1-3_all.deb (--unpack):
 unable to stat './data/data/com.termux/files' (which was about to be installed): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/00-libffi_3.4.4_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/01-libxml2_2.10.3_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/02-libllvm_15.0.7_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/03-libcompiler-rt_15.0.7_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/04-lld_15.0.7_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/05-llvm_15.0.7_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/06-ndk-sysroot_25b-3_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/07-clang_15.0.7_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/08-gdbm_1.23_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/09-glib_2.74.5_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/10-libandroid-posix-semaphore_0.1-3_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/11-libcrypt_0.2-5_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/12-make_4.4_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/13-ncurses-ui-libs_6.4-1_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/14-pkg-config_0.29.2-2_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/15-python_3.11.1-2_aarch64.deb
 /data/data/vn.vhn.vsc/files/tmp/apt-dpkg-install-eycdPu/16-python-pip_22.3.1-3_all.deb
E: Sub-process /data/data/vn.vhn.vsc/files/usr/bin/dpkg returned an error code (1)

**Comment by vhqtvn** [comment]
Seems that you used termux scripts to change repo to termux's, restart the application so VHEditor can try to fix the repo itself, if it doesnt work fix yourself the repos in `/data/data/vn.vhn.vsc/files/usr/etc/apt/`. Or the fastest way is reset rootfs.
