### ISSUE TITLE
Any way to change the zoomLevel?

### ISSUE THREAD

**Issue by fearthecowboy** [vhqtvn/VHEditor-Android#23]
I find the UI size is a bit much -- is there any way to adjust the zoomLevel?

I can change the editor and terminal `fontSize` in the settings, but zoomLevel ain't there :(

**Comment by vhqtvn** [comment]
Hm ok i'll check if it can be changed.

**Comment by bithooked** [comment]
If you're using in Dex, I've noticed that the Dex font settings do affect the font size of the entire UI in VHE.  It would be much nicer to support zoom directly though.

**Comment by sopyb** [comment]
I will be working on this
