### ISSUE TITLE
Unable to use intermediary scaling page

### ISSUE THREAD

**Issue by andrew-c0** [vhqtvn/VHEditor-Android#231]
When using the app, I am unable the get to the intermediary state where I can set the instance's scaling and other options. I barely see a glimpse of it and then I'm thrown into the UI Coding instance. Is that intended?

Steps to reproduce:
- Use latest version available (2.14.1 - arm64)
- Install code
- click on `start editor`
- an intermediary screen containing scaling options , virtual mouse and other options appear (for a couple of miliseconds)
- the screen loads up the editor

Device:
- Samsung Galaxy Tab S8, Android 13.

I would like to help out with more info, if you need any help.

**Comment by vhqtvn** [comment]
You can show that screen again by 3 fingers slide up.
