### ISSUE TITLE
Could not connect to vsc.vhn.vn:443 (167.99.29.27). - connect (111: Connection refused)

### ISSUE THREAD

**Issue by AlexanderZhelnin** [vhqtvn/VHEditor-Android#233]
I'm trying install nodejs but embaded termux return this error

![image](https://user-images.githubusercontent.com/88617468/224427363-78d298a3-b311-4bcc-9b53-7ff22a3a67ca.png)

**Comment by vhqtvn** [comment]
The server is functioning, maybe your network is blocking it?
