### ISSUE TITLE
How to access downloads folder?

### ISSUE THREAD

**Issue by GustavoGomez092** [vhqtvn/VHEditor-Android#247]
Hi! First of all... What a great app! 
This may be a noob question, but I just can't find a way to access the internal storage from within the terminal or the code editor. Any help is appreciated! Thanks!

**Comment by HGRgamer** [comment]
You can access internal storage folder using /storage/emulated/0
This will work on both code-editor and terminal
For specifically downloads folder use /storage/emulated/0/Download

In case you want to know how to find it , I suggest you to use a file access app like NMM storage from playstore and select any file and click on properties , then you can see/copy the path of the selected file.

**Comment by GustavoGomez092** [comment]
Thank you so much! got it working in a sec! a simple ```cd /storage/emulated/0/Download``` is all I needed! thanks a gain!
