### ISSUE TITLE
Set path

### ISSUE THREAD

**Issue by uudashr** [vhqtvn/VHEditor-Android#25]
Is there a way to set PATH?

I'm install go plugin, then it requires me to install golang manually using command line.
Then the plugin prompt me to install go tools, which already done, it just that the binary of the tools are not in the PATH. The plugin always fail when try to invoke the tool

**Comment by vhqtvn** [comment]
Ok i'll add ~/.profile reading in next version.

**Comment by vhqtvn** [comment]
Hi sorry for late update, I added ~/.profile reading in 1.1.14.
