### ISSUE TITLE
Bring (or return) Scale (`ZoomLevel`) Functionality

### ISSUE THREAD

**Issue by yeskiy** [vhqtvn/VHEditor-Android#265]
Hey!

I am an enthusiastic user of VHEditor and find it incredibly useful for coding on my mobile device. However, I'm facing a challenge with the small size of editor elements like buttons and drop-downs on my screen, which sometimes hinders the ease of use.

I kindly request the addition of a UI scaling or zoom functionality to VHEditor. This feature would allow users to adjust the size of interface elements, ensuring a more comfortable and accurate interaction, especially on devices with varying screen sizes. This enhancement would greatly improve the overall user experience and make VHEditor even more valuable.

**Comment by HGRgamer** [comment]
The app already has this feature
To access it press and hold your finger on the bottom right corner of the screen after Start Editor (its an overlay with "Fn" written on it, visible only when you click on the screen)
From there click on config and a menu will open up with the option to change ui scale , mouse scale , and other settings. It also shows logs of the code-server.
