### ISSUE TITLE
Consider to use own bootstrap archives instead of hosted by Termux

### ISSUE THREAD

**Issue by xeffyr** [vhqtvn/VHEditor-Android#28]
Currently you are using our bootstrap archives for your project. Consider to build and use your own bootstrap archive and apt repository.

https://github.com/vhqtvn/VHEditor-Android/blob/9ac7100daa4b44a67e382e8acbe37d0bb80099f1/app/build.gradle#L119

***

Bootstrap archives can be built by using this script: https://github.com/termux/termux-packaging/blob/2759e044fb0e7b679127a94dec225d9f28ac61d4/scripts/generate-bootstraps.sh. You will need to [change few variables](https://github.com/termux/termux-packaging/blob/2759e044fb0e7b679127a94dec225d9f28ac61d4/scripts/generate-bootstraps.sh#L20-L24) as required by your project and then just execute script on any Linux-based machine. You will also need an apt repository before attempting to get bootstrap zips.

**Comment by vhqtvn** [comment]
Hm yes currently VHEditor just use binary from Termux with a wrapped dpkg that will patch all extracted files from `/data/data/com.termux` into `/data/data/vn.vhn.vsc` after install, it's working for most packages I'm using. Maintain an independent repository may take much effort, i'll try to find some time looking into it.

**Comment by iAdanos** [comment]
You can consider starting code-server from inside proot-distro environment. 
IDE's terminal will then run inside this distro and there will be no issues with packages install (e,g,: ubuntu arm packages will be installed from official repos, not termux-ones).
Then it's enough to configure termux to have all needed extensions (especially proot-distro), and after code-server start it will be not needed anymore.
Makes sense?

**Comment by vhqtvn** [comment]
Done.
