### ISSUE TITLE
Node.js not installing 

### ISSUE THREAD

**Issue by Mak1319** [vhqtvn/VHEditor-Android#280]
node.js is not installing.
After that showing ..
```sh 
CANNOT LINK EXECUTABLE "node": library "libicui18n.so.73" not found: needed by main executable
```
![Screenshot_2024-01-07-19-50-14-113_vn vhn vsc](https://github.com/vhqtvn/VHEditor-Android/assets/78523112/e5cef688-ee67-4238-ba3e-25b0fbf602bc)

**Comment by Ahmadrezalbs** [comment]
Same for me

**Comment by Ahmadrezalbs** [comment]
Install the libicu v73.2 to fix this problem :
- [ ] apt-get install libicu=73.2

**Comment by Mak1319** [comment]
Fixed
