### ISSUE TITLE
Samsung DEX Two Seperate Cursors

### ISSUE THREAD

**Issue by risedangel** [vhqtvn/VHEditor-Android#284]
First of all thank you for that amazing app.
When i try to run the app with samsung dex, the app has its own cursor and i have my physical cursor within the app, so there are two cursors and the app fails to work. Can we remove the in app cursor ?

**Comment by rosostolato** [comment]
While you are starting the editor, there's a checkbox to enable/disable virtual mouse. You need to disable it quickly.

**Comment by ezra-1** [comment]
Please close this issue
