### ISSUE TITLE
I cant use expo 

### ISSUE THREAD

**Issue by kaderisoft** [vhqtvn/VHEditor-Android#29]
I executed this command 'npm install -g expo-cli' and it is done, but when using 'expo init myProject' it is does not work 

and error on use " apt upgrade"

**Comment by xeffyr** [comment]
Apt issues are related to the fact that VHEditor uses [Termux](https://github.com/termux) repositories instead of its own.

All binaries contain hardcoded references to Termux-specific locations and they can't be changed at runtime.
```
~/extracted $ dpkg-deb -x nodejs_14.8.0-1_aarch64.deb nodejs
~/extracted $ strings nodejs/data/data/com.termux/files/usr/bin/node | grep /com.termux/ | head -n 20
/data/data/com.termux/files/usr/lib
/data/data/com.termux/files/usr/bin/login
/data/data/com.termux/files/usr/bin/bash
/data/data/com.termux/files/home
/data/data/com.termux/files/usr/tmp/__v8_gc__
/data/data/com.termux/files/usr/tmp
TMPDIR=/data/data/com.termux/files/usr/tmp
/data/data/com.termux/files/usr/tmp/tmpfile.%d-%u
        file = '/data/data/com.termux/files/usr/bin/sh';
           '/data/data/com.termux/files/usr/tmp';
                       "include_dirs": [ "/data/data/com.termux/files/usr/include",
                                         "/data/data/com.termux/files/usr/include",
                                         "/data/data/com.termux/files/usr/include",
                                         "/data/data/com.termux/files/usr/include"],
                       "libraries": [ "-L/data/data/com.termux/files/usr/lib",
                                      "-L/data/data/com.termux/files/usr/lib",
                                      "-L/data/data/com.termux/files/usr/lib",
                                      "-L/data/data/com.termux/files/usr/lib",
                 "node_prefix": "/data/data/com.termux/files/usr",
CJ/data/data/com.termux/files/usr/tmp/perf-%d.map
```
This leads to number of path-related issues, so you may observe problems with installing packages.

I hope that @vhqtvn will implement suggestions from https://github.com/vhqtvn/VHEditor-Android/issues/28 and will provide packages compatible with VHEditor.

**Comment by vhqtvn** [comment]
@kaderisoft 
1. `npm -g` install binary into `/data/data/vn.vhn.vsc/files/bin` which havent included in PATH, i added in latest version.
2. After updating to latest version, the expo script at `/data/data/vn.vhn.vsc/files/bin` use shebang `/usr/bin/env` which doesnt exist, you should edit that file and change shebang to `/data/data/vn.vhn.vsc/files/usr/bin/env`.
