### ISSUE TITLE
Differences from running on termux.

### ISSUE THREAD

**Issue by Deshdeepak1** [vhqtvn/VHEditor-Android#30]
This is more a question rather than issue.
If I use code-server directly on termux, it works but terminal inside editor doesn't open and exetensions don't load, gives __atomic_add* not found error.
 What have you done that it works?

**Comment by vhqtvn** [comment]
I'm not sure what's different, my method is cross compiling node and gyps of code-server for each arch. Maybe the bundled code-server dont have gyp compiled.
