### ISSUE TITLE
Can't Install Any Packages

### ISSUE THREAD

**Issue by AryaReal1** [vhqtvn/VHEditor-Android#305]
It seems some dependencies are unmet, and also error file.
```sh
~ $ node
node: command not found
```
```sh
~ $ pkg i nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libcurl : Depends: openssl (>= 1:3.2.1-1) but 3.0.5 is to be installed
 nodejs : Depends: c-ares but it is not going to be installed
          Depends: libicu but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```
```sh
~ $ apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  c-ares curl libcurl openssl
The following NEW packages will be installed:
  c-ares
The following packages will be upgraded:
  curl libcurl openssl
3 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/3625 kB of archives.
After this operation, 2458 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: error: parsing file '/data/data/vn.vhn.vsc/files/usr/var/lib/dpkg/status' near line 601 package 'psmisc':
 'Version' field value '23.7-': revision number is empty
E: Sub-process /data/data/vn.vhn.vsc/files/usr/bin/dpkg returned an error code (2)
```
App version `2.18.1-0 arm64`

**Comment by vanhoavn** [comment]
rm /data/data/vn.vhn.vsc/files/usr/var/lib/dpkg/status


________________________________
From: AryaReal ***@***.***>
Sent: Sunday, October 13, 2024 8:59:58 PM
To: vhqtvn/VHEditor-Android ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vhqtvn/VHEditor-Android] Can't Install Any Packages (Issue #305)


It seems some dependencies are unmet, and also error file.

~ $ node
node: command not found

~ $ pkg i nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libcurl : Depends: openssl (>= 1:3.2.1-1) but 3.0.5 is to be installed
 nodejs : Depends: c-ares but it is not going to be installed
          Depends: libicu but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

~ $ apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  c-ares curl libcurl openssl
The following NEW packages will be installed:
  c-ares
The following packages will be upgraded:
  curl libcurl openssl
3 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/3625 kB of archives.
After this operation, 2458 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: error: parsing file '/data/data/vn.vhn.vsc/files/usr/var/lib/dpkg/status' near line 601 package 'psmisc':
 'Version' field value '23.7-': revision number is empty
E: Sub-process /data/data/vn.vhn.vsc/files/usr/bin/dpkg returned an error code (2)

App version 2.18.1-0 arm64
