### ISSUE TITLE
Is there any intended way to change server address or exit current workspace?

### ISSUE THREAD

**Issue by chigix** [vhqtvn/VHEditor-Android#32]
I'm using [Code-Server](https://github.com/cdr/code-server) directly with VHEditor, where one interaction design that I'm currently confused is how to exit current editor screen or change to another editor on another server?

Because I cant find any extended UI to close current workspace and take me back to home screen of VHEditor, I have to tap android's system `back` button continuously until VHEditor shows it's initial screen where I can input server address. Is this interaction expected by this repository's initial design or planning ?

**Comment by vhqtvn** [comment]
Yes that's intended. Do you have any suggestion?
