### ISSUE TITLE
termux prefix wrong?

### ISSUE THREAD

**Issue by xerxes9000sx** [vhqtvn/VHEditor-Android#33]
app version: 1.1.14 (GooglePlay)
android: 8.1.0(phone) & 8.0.0(tablet)

App launches and installs code-server without problems, but built-in termux pkg command fails to install/update any package with error:
```
Warning: aborting execution because /data/data/com.termux/files/usr is not accessible.
Please make sure that program is compiled with correct prefix.
```
Granted storage permission in app setting, Wiped app data&cache, but still no success.
Version 1.1.13 from github also shows same storage access error.
Veriosn 1.1.12 from github works fine.

Any option to override path for bundled termux inside terminal?

**Comment by xeffyr** [comment]
I have opened the related issue here: https://github.com/vhqtvn/VHEditor-Android/issues/28.

We don't allow use of our (@termux) hosting capabilities by third-party projects (for personal use is ok however). Now we have added prefix check as lite preventive measure.

**Comment by vhqtvn** [comment]
Latest version should work now.
