### ISSUE TITLE
'pkg install git' failed 

### ISSUE THREAD

**Issue by timiil** [vhqtvn/VHEditor-Android#36]
hello, i am running the APP on a Huawei MatePad Pro, the current server version is shown: 202006100100 ,  when i try to install the git into App, it is failed by some permission problem ?
 
![Screenshot_20201124_124608_vn vhn vsc](https://user-images.githubusercontent.com/6621768/100049925-62390780-2e53-11eb-8720-4f24c7274be2.jpg)
![Screenshot_20201124_124648_vn vhn vsc](https://user-images.githubusercontent.com/6621768/100049930-6533f800-2e53-11eb-82ce-30a9655db8bd.jpg)

**Comment by xeffyr** [comment]
That's just a misuse of Termux repositories, https://github.com/vhqtvn/VHEditor-Android/issues/33#issuecomment-707091904.

**Comment by timiil** [comment]
so, how can i install git into VHEditor that let me pull and push code from my git repo ? please tell us the solution :)

**Comment by xeffyr** [comment]
Author of VHEditor should stop use of https://dl.bintray.com/termux/termux-packages-24/ and any of its mirrors.

Termux project (@termux) uses a patched version of `apt` which will refuse to work if not running within the original prefix. You may look the patch file (https://github.com/termux/termux-packages/blob/master/packages/apt/0012-verify-prefix.patch.txt) to see what's going on. *Third-parties are not allowed to use Termux binary apt repositories, except for private use.*

**Comment by kerokhin88** [comment]
dirty fix
`sed -i 's/\x65\x72\x6D\x75\x78\x2F\x66\x69\x6C\x65\x73\x2F\x75\x73\x72\x00\x2F\x64\x61\x74\x61\x2F\x64\x61\x74\x61\x2F\x63\x6F\x6D\x2E\x74\x59\x6F\x75\x20/\x6E\x2E\x76\x73\x63\x2F\x66\x69\x6C\x65\x73\x2F\x75\x73\x72\x00\x2F\x64\x61\x74\x61\x2F\x64\x61\x74\x61\x2F\x76\x6E\x2E\x76\x68\x59\x6F\x75\x20/g' /data/data/vn.vhn.vsc/files/usr/bin/apt`
until separate repo is ready.

**Comment by bithooked** [comment]
@kerokhin88 Any idea how you paste that into the VHE terminal?  I can't seem to do it and if I have to type that by hand I'm going to cry.

**Comment by kerokhin88** [comment]
something like
` curl -s https://pastebin.com/raw/wxA7LyDa | bash`
But remember not all termuxpackages will work fine.
See install wrapper https://github.com/vhqtvn/VHEditor-Android/blob/master/app/src/main/res/raw/dpkg_wrapper.bin

**Comment by fawadahmad111** [comment]
It's frustrating

**Comment by vhqtvn** [comment]
Latest version should work now.
