### ISSUE TITLE
How to install java?

### ISSUE THREAD

**Issue by sinojelly** [vhqtvn/VHEditor-Android#42]
I tried to install java following this link: 
https://stackoverflow.com/questions/61720889/how-can-i-install-java-runtime-on-android-device

When I run this command:
apt-get install -y ./openjdk-9-jre-headless_9.2017.8.20-1_arm.deb

It says: Reading package lists  Error. please see the picture below.
Any help would be appreciated!
![Screenshot_20210116_125620_vn vhn vsc](https://user-images.githubusercontent.com/520711/104797714-30ad3e80-57fb-11eb-890b-ee5cc6f105d1.jpg)

**Comment by anonimo82** [comment]
Please, try this:

https://github.com/MasterDevX/Termux-Java

Cheers

**Comment by anonimo82** [comment]
Have you made it?

**Comment by sinojelly** [comment]
@anonimo82 Termux-Java can not work. (I use Huawei MatePad pro, android 10)

I almost tried all the solutions listed in this link, no one success.
https://stackoverflow.com/questions/61720889/how-can-i-install-java-runtime-on-android-device

I also found a disable package here, but compiling it is a bit complicated, maybe also can not work.
https://github.com/termux/termux-packages/tree/master/disabled-packages/openjdk-9-jre-headless

**Comment by anonimo82** [comment]
Why can't it work? VHEditor embeds Termux
