### ISSUE TITLE
Run Python and minor issues

### ISSUE THREAD

**Issue by anonimo82** [vhqtvn/VHEditor-Android#44]
Hello everyone, I didn't understand how to run Python code from this.
Terminal won't open, and some menu items don't work (like, in example, file -> open folder)

I'd like to stick with this fully featured editor, I've been looking for something similar for ages.

Thanks in advance for any help.

Bye, Ivano.

**Comment by anonimo82** [comment]
Ok, don't know how, but now terminal and what wasn't working, works ok.
But, on terminal, trying to even just doing a "pkg update", this is what happens:

```$ pkg update
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Warning: aborting execution because /data/data/com.termux/files/usr is not accessible.
Please make sure that program is compiled with correct prefix.
$ ```

**Comment by anonimo82** [comment]
Anyone?

**Comment by anonimo82** [comment]
Bumo

**Comment by anonimo82** [comment]
Still waiting for help...

**Comment by anonimo82** [comment]
Hey

**Comment by anonimo82** [comment]
@vhqtvn help

**Comment by vhqtvn** [comment]
Sorry i has been too busy recently, dont have time left for this project :( The problem is due to termux to implement checks that prevent non-termux applications to use their packages, i'm trying to build my own repository but it need time...

**Comment by anonimo82** [comment]
Ok, please, keep me updated

**Comment by vhqtvn** [comment]
Hi, please try the latest version now, the problem should be fixed.

**Comment by anonimo82** [comment]
No, I can't neither run the editor now.
