### ISSUE TITLE
Installing extensions 

### ISSUE THREAD

**Issue by Xandor19** [vhqtvn/VHEditor-Android#45]
I've been trying to install extensions like in linux/windows vs code using the marketplace, but It raises an 403 error so I did like the app says and downloaded the .vsix file manually, but when I opened the Install with VSIX component and I selected the the file, nothing happened and it said that no extensions were been installed.

I would like to know can I install those extensions or if I must install others different to the vs code marketplace options. I've found this app to be just what I needed to my career but I could use the extensions

**Comment by vhqtvn** [comment]
There should be no more problem in latest version, please reopen if you still facing the problem.
