### ISSUE TITLE
Error=13 permission denied

### ISSUE THREAD

**Issue by sopyb** [vhqtvn/VHEditor-Android#51]
since 1.2.0 the manifest value for target sdk was changed to 29 and from sdk 29 and forward don't allow running scripts from the app's home directory... I could get it working just fine on my redmi note 9s with a older version of the app (I'm sorry if I'm mistaken of the cause of this, this is what I found with a little research on the issue)

The log in app is:
Starting... listenOnAllInterface=false

Exception: java.io.IOException: Cannot run program "/data/data/vn.vhn.vsc/files/ usr/bin/bash": error=13, Permission denied Finished.

Let me know if I should provide any more info.

**Comment by GenBill** [comment]
I meet the same problem

**Comment by vhqtvn** [comment]
For android 10+ please install latest version from github release.
