### ISSUE TITLE
Can't git clone private repos despite being logged into my github account.

### ISSUE THREAD

**Issue by sopyb** [vhqtvn/VHEditor-Android#56]
# Problem
Here's the error message I am getting and the git terminal log

![IMG_20210616_082759.jpg](https://user-images.githubusercontent.com/32602702/122162978-1e543100-ce7d-11eb-884e-06aff468603a.jpg)
**Transcript**: Git: fatal: cannot exec /data/data/vn.vhn.vsc/files/code-server/release standalone/lib/vscode/extensions/git/dist/askpass.sh': Permission denied

![IMG_20210616_082850.jpg](https://user-images.githubusercontent.com/32602702/122162990-290ec600-ce7d-11eb-873e-da28d137ba9c.jpg)
**Transcript**: 
git clone https://github.com/sopyb/TIC.git /data/data/vn.vhn.vsc/files/home/TIC --progress

Cloning into '/data/data/vn.vhn.vsc/files/home/TIC'. · ·|

fatal: cannot exec '/data/data/vn.vhn.vsc/files/code-server/release-standalone/lib/vscode/extensions/git/dist/askpass.sh': Permission denied

fatal: could not read Username for 'https://github.com':

No such device or address

# Device
Device model: Xiaomi Redmi note 9S (Pro India) (codenamed Curtana)
Operating system: MIUI 12.1 based on Android 10

If there's any other info I should provide please let me know

**Comment by vhqtvn** [comment]
You should use `git clone git@` instead of https.
I'll take a look into askpass.sh later.
