### ISSUE TITLE
PHP command error

### ISSUE THREAD

**Issue by DayvidPlays** [vhqtvn/VHEditor-Android#59]
im installed php intellisense and php from terminal, on restart this errot appears

Error spawning PHP: Command failed: php --version
CANNOT LINK EXECUTABLE "php": library "libicuio.so.68" not found: needed by main executable
![Screenshot_20210708-023824_VHEditor](https://user-images.githubusercontent.com/70015378/124868094-a49ff680-df95-11eb-8ddb-0491440bed2e.png)

**Comment by vhqtvn** [comment]
Seems that upstream termux has this problem too, i'll check soon.

**Comment by vhqtvn** [comment]
Please run apt update and upgrade php, should be fixed.
