### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by ghost** [vhqtvn/VHEditor-Android#62]
When I restart my phone and try to open the app, as soon as I click to open it it closes and appears: VH Editor crashes constantly, and only when I reinstall the app does it work again

**Comment by vedant-9** [comment]
Hey devlopers,
I am also facing this issue. Everytime I restart the phone so crashes and we have to reinstall it
Please help

**Comment by Xandor19** [comment]
I have the same issue, but it happens without even restarting my device. Sometimes after a while just crashes and I have to re-download (I'm downloading the apk directly from here as recommended, when this happens and I try to reinstall using that same apk it keeps crashing and I have to download it again from here)
