### ISSUE TITLE
Python Extension Not Working

### ISSUE THREAD

**Issue by 99900999** [vhqtvn/VHEditor-Android#66]
![Screenshot_2021-08-01-13-15-01-914_vn vhn vsc](https://user-images.githubusercontent.com/83855443/127762640-8df3d673-1a65-4a4f-9378-17246d4679d7.jpg)

> It's showing this all the time, though I've installed python from vscode terminal. 
> I've selected python interpreter path as 
```sh
/data/data/vn.vhn.vsc/files/usr/bin/python
```
Even though it didn't worked.

**Comment by vhqtvn** [comment]
Please open View/Output, select python and check the output.

**Comment by 99900999** [comment]
![Screenshot_2021-08-20-00-20-33-961_vn vhn vsc](https://user-images.githubusercontent.com/83855443/130123320-3cc5bc60-d8ae-4ece-8ac7-95f04e035c86.jpg)
![Screenshot_2021-08-20-00-20-28-770_vn vhn vsc](https://user-images.githubusercontent.com/83855443/130123353-44c84654-633d-4704-a71c-ffe1ea50bdc0.jpg)


> Permission denied,

But it has storage permission

![Screenshot_2021-08-20-00-21-59-317_com google android permissioncontroller](https://user-images.githubusercontent.com/83855443/130123526-6ad78776-4554-4bd0-ac57-429122f889dc.jpg)

**Comment by 99900999** [comment]
@vhqtvn

**Comment by vhqtvn** [comment]
Hmm strange, can you run scandir in terminal?

**Comment by 99900999** [comment]
> Hmm strange, can you run scandir in terminal?

![Screenshot_2021-08-21-11-01-05-227_vn vhn vsc](https://user-images.githubusercontent.com/83855443/130311156-d20d537b-96a0-48ba-a345-73a872dd645c.jpg)

**Comment by vhqtvn** [comment]
Do you have "Anaconda Extension Pack by Microsoft" installed?
https://stackoverflow.com/questions/62220904/vs-code-python-installation-and-python-interpreter-not-recognized

**Comment by 99900999** [comment]
> Do you have "Anaconda Extension Pack by Microsoft" installed?
> https://stackoverflow.com/questions/62220904/vs-code-python-installation-and-python-interpreter-not-recognized

No, I just downloaded python extension.

**Comment by vhqtvn** [comment]
Strange, i cant reprocedure the bug in any of my devices.
Please run python in the terminal, check if it can run.
Try running `apt update` and then `apt install python` again.

**Comment by 99900999** [comment]
> Strange, i cant reprocedure the bug in any of my devices.
> Please run python in the terminal, check if it can run.
> Try running `apt update` and then `apt install python` again.

BTW my android version is `Android-11`
Device: `Xiaomi Note 10 Lite`

![Screenshot_2021-08-22-10-27-03-269_vn vhn vsc](https://user-images.githubusercontent.com/83855443/130342293-fe07506b-f7a7-4b39-abc0-c280bafbb627.jpg)

**Comment by 99900999** [comment]
![Screenshot_2021-08-22-10-35-43-231_vn vhn vsc](https://user-images.githubusercontent.com/83855443/130342474-913cb193-f793-46bd-9aef-0fe4c4dca18b.jpg)

``` diff
- Still same error....
```

**Comment by vhqtvn** [comment]
What's the output of running `python` in console? Is there any error?

**Comment by 99900999** [comment]
> What's the output of running `python` in console? Is there any error?

![Uploading Screenshot_2021-08-24-09-50-24-406_vn.vhn.vsc.jpg…]()

**Comment by 99900999** [comment]
> What's the output of running `python` in console? Is there any error?

![Screenshot_2021-08-24-09-50-24-406_vn vhn vsc](https://user-images.githubusercontent.com/83855443/130553063-cbae6e99-0397-42e5-afd7-06c08c862ef5.jpg)

**Comment by vhqtvn** [comment]
just type `python`?

**Comment by 99900999** [comment]
Steps I followed.

1. Installed VHEditor
2. Gave storage permission
3. Installed Python Extension `ms-python`
4. Installed Python in terminal through `pkg install python`
5. Restarted VHEditor
6. And always having bug that says `Select Interpreter`
7. In terminal it says permission denied

`Android version: 11`

**Comment by 99900999** [comment]
![Screenshot_2021-08-27-09-43-37-378_vn vhn vsc](https://user-images.githubusercontent.com/83855443/131236617-98d7dcc1-d592-4a88-9bfd-089840be7baa.jpg)

No problem with `python` command. :)

**Comment by vhqtvn** [comment]
Works now. Check current version.

**Comment by Sagor057** [comment]
Why python extension not supurt to create venv environment on "sdcard/newfolder"
the storage permission is allow also

**Comment by BenjunOgania** [comment]
i also have a problem with the new version
![Screenshot_2024-01-01-08-34-44-27_9c1589490c906a9623165cad7a860a58](https://github.com/vhqtvn/VHEditor-Android/assets/147109546/c03f343d-637f-492d-9a7d-01f58aa6fbd1)

**Comment by BenjunOgania** [comment]
need some help

**Comment by LifesActor** [comment]
> من هم با نسخه جدید مشکل دارم ![اسکرین شات_2024-01-01-08-34-44-27_9c1589490c906a9623165cad7a860a58](https://private-user-images.githubusercontent.com/147109546/293526269-c03f343d-637f-492d-9a7d-01f58aa6fbd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzUzODcsIm5iZiI6MTcwNzM3NTA4NywicGF0aCI6Ii8xNDcxMDk1NDYvMjkzNTI2MjY5LWMwM2YzNDNkLTYzN2YtNDkyZC05YTdkLTAxZjU4YWE2ZmJkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwNjUxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2M2ZGI3OGI1NTQyNmY1OWRjY2RhMmUyMTQ2ODljYmQ4NWU5MmQ4YzhjODc3M2JhNTc3Nzk3MGYzMTZkZjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FOjbsw3vy_F-gJpdam5AUuVioweu7wQjd_DUgmo5Uao)

me too
