### ISSUE TITLE
does not install 

### ISSUE THREAD

**Issue by Spit-fires** [vhqtvn/VHEditor-Android#70]
tried default android parser didnt work so tried sai got this error
![Screenshot_20210815-231012_SAI.jpg](https://user-images.githubusercontent.com/84981998/129486628-73f2b7f6-877d-4cec-b83c-5231869796c9.jpg)

**Comment by vhqtvn** [comment]
seems that your download is corrupted, please retry downloading.

**Comment by Spit-fires** [comment]
thank you it worked
