### ISSUE TITLE
[BUG] npm command non working

### ISSUE THREAD

**Issue by D4yv1dKK** [vhqtvn/VHEditor-Android#71]
I tried using the `npm init -y` command and it came up:

[Print here](https://drive.google.com/file/d/10IatSYtFM0r6kogsRU33v6JTbO7tIQ5Y/view?usp=drivesdk)

**Comment by vhqtvn** [comment]
Please try to install again with libicu

```
apt update
apt install nodejs libicu
```

Reopen the issue if the problem still occurs.
