### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by amiria703** [vhqtvn/VHEditor-Android#75]
Hi
Thanks for your great work 👍
I used to use your great app on my Sony Xperia Z5 android 7.1.1
It really worked great there but now I switched to an Android 11 device
In this new device first I've installed your app from Play Store, and I saw that error
Second I tried again to install latest version from GitHub this time Your app keeps stopping
I'm waiting for its fix
Thanks 🙏

**Comment by vhqtvn** [comment]
Hm what can you do before it stopped?

**Comment by amiria703** [comment]
Sorry for that, that was a fresh install, Seems suspicious but now It opens and looks like it will work as expected.

**Comment by vhqtvn** [comment]
Great you had it worked!
