### ISSUE TITLE
Git repo clone crash

### ISSUE THREAD

**Issue by Xandor19** [vhqtvn/VHEditor-Android#80]
I tried to clone a repo in the vs code traditional way, choosing the option and then following the link to autorize the app. It works fine and I get to the point where the web page shows "You can close this tab now". When I return to VHEditor and start typing at the search bar (or wait a few secconds), this happens

![Screenshot_20210831-192051_VHEditor](https://user-images.githubusercontent.com/77125505/131550356-295c108e-9fa2-4fa5-be8f-cfafdc0276ae.jpg)

After the page reloads, if I select the Clone Repository option again (like I did at the begining) it just starts the process from scratch (only that when I open the browser to authorize goes directly to the "You can close this tab now" page) and happens again

Note: The "Singing in to github.com..." message at the bottom bar appears when the "clone from github" option is selected at the search bar and stays until the page is reloaded after the error. Also, the Accounts Button above the setting button only shows "loading" indefinitely when clicked

**Comment by sopyb** [comment]
Seem chromium is seeing the connection as a security threat. I will try to fix this today or tomorrow

**Comment by sopyb** [comment]
cdr/code-server#4217

not fixable... tho there is a work around

1) Clone from github
2) Allow 'Github' extension to sing in using Github
3) Press cancel
4) Click "Singing in to github.com" in the bottom bar next to ip of server you're connected to (default 127.0.0.1:13337)
5) Paste in a github token [(you can get one here)](https://github.com/settings/tokens)
