### ISSUE TITLE
Not opening in Android 11

### ISSUE THREAD

**Issue by abuhabban** [vhqtvn/VHEditor-Android#81]
![Screenshot_2021_0902_184141](https://user-images.githubusercontent.com/70461458/131849666-009be366-2b09-4da5-ac83-2762447dc1eb.png)

I am using vivo y12 4/64gb.
What should i need to install.

**Comment by sopyb** [comment]
You should install the `VHSCode-arm64.apk` for you cpu.

Could you provide more info about how it's not opening? like if you got past installing the apk or if you managed to install the server and maybe the client won't load
