### ISSUE TITLE
Cannot update npm to 7.x

### ISSUE THREAD

**Issue by jhmaster2000** [vhqtvn/VHEditor-Android#82]
I have installed node and npm through `apt install nodejs`, it works nicely, however after a lockfile conflict i noticed the npm version installed was 6.x, which uses lockfile v1, while my project uses lockfile v2, used by npm 7.x

I attempted to update npm through the usual method, running `npm install -g npm@7` which then prompted me to run `npm install -g npm` and I did so. Both commands gave out ordinary success messages.

However upon closing the current terminal and opening a new one, the `npm` command no longer worked, instead giving out a "No such file or directory" error.

Running `whereis npm` revealed there were now two registered links for the "npm" command, as follows:
```
/data/data/vn.vhn.vsc/files/usr/bin/npm
/data/data/vn.vhn.vsc/files/bin/npm
```
The top one being the old npm 6.x, which calling directly with the full path worked, and the bottom one which was being called upon running "npm" was supposedly npm 7.x, or where it should have been, but as the error said, the file did not exist.

Running `unlink` on the supposed npm 7.x path fixed the issue of "npm" command not working, but it simply reverted to npm 6.x, which takes me back to square one.

Android version: 10
Phone: Galaxy A72

**Comment by sopyb** [comment]
this might be a dumb reply but have you tried [fnm](https://github.com/Schniz/fnm)?

it might just work to install node 16 (that comes with npm 7)
