### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by anonimo82** [vhqtvn/VHEditor-Android#95]
Hello everyone.
How can I use VHEditor to build Android Studio projects?

Thanks in advance for any help.

Edit: I found this: https://github.com/termux/termux-packages
But I get an error with script setup-android-sdk.sh 

I'm uploading a screenshot because I can't copy the error
![Screenshot_20211011-172327_Chrome](https://user-images.githubusercontent.com/38261009/136815926-a0acacc3-182a-4598-9dc2-995f385a437d.jpg)

And I installed Android extension

**Comment by Sp4Rx** [comment]
Could you show your android script?
I assume you need to install Android SDK. For reference check how to install Android SDK on Ubuntu

**Comment by vhqtvn** [comment]
It's the same as termux, if you can build in termux you can build in the editor.

I think as java is still experimental in termux Android projects building cant be fully supported. But the problem should be asked on termux repo anyway.
