### ISSUE TITLE
When I try "pkg install xxx", it reports an error(v1.5.0)

### ISSUE THREAD

**Issue by shanyan-wcx** [vhqtvn/VHEditor-Android#97]
error creating directory './data/data/com.termux': Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
/data/data/vn.vhn.vsc/cache/apt/archives/git_2.33.I_aarch64.deb
E: Sub-process /data/data/vn.vhn.vsc/fites/usr/bin/dpkg returned an error code (1)

**Comment by shanyan-wcx** [comment]
And "apt update" report another error

Ign:1 https://vsc.vhn.vn/game-packages-24 games InRelease
Hit:2 https://packages.termux.org/apt/termux-main stable InRelease
Ign:3 https://vsc.vhn.vn/science-packages-24 science InRelease
Err:4 https://vsc.vhn.vn/game-packages-24 games Release
404 Dont find :p [IP: 128,199.243.164 443]
Err:5 https://vsc.vhn.vn/science-packages-24 science Release
404 Dont find :p [IP: 128,199.243.164 443]
Reading package lists... Done
E: The repository 'https://vsc.vhn.vn/game-packages-24 games Release' does not have a Release 
file.
N: Metadata integrity can't be verifiedt repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://vsc.vhn.vn/science-packages-24 science Release' does not have a Re 
lease file.
N: Metadata integrity can't be verifiedr repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Mecha-Labs** [comment]
Therefore I use version 1.4.4

**Comment by kde99** [comment]
These repos doesn't exist on his website easiest fix (unless you need stuff from them) is to comment them from the repo index. Open the editor and open a terminal then edit the files in /data/data/vn.vhn.vsc/files/usr/etc/apt/sources.list.d . Either comment the lines or remove the files then apt will work.

**Comment by hamncheez** [comment]
Any update on this? I updated 

`https://vsc.vhn.vn/packages`

to

`https://vsc.vhn.vn/termux-packages-24/`

since thats where it was redirecting anyways, but both give 401.

**Comment by shanyan-wcx** [comment]
pkg install seems to be OK, but I only tried it once. The problem of apt update still exists

**Comment by EgorCloud** [comment]
Same problem

**Comment by vhqtvn** [comment]
Fixed in latest version.
