### ISSUE TITLE
How to install extension in vheditor 1.60

### ISSUE THREAD

**Issue by Nafisz** [vhqtvn/VHEditor-Android#99]
every time I want to download the extension it always fails with the reason it is not compatible please answer

**Comment by Mecha-Labs** [comment]
try Installing the Extension with the vsix file

**Comment by Amu757** [comment]
Is this ishue removed or not ?
 Can you explain about use of vsix file

**Comment by NEK-RA** [comment]
@Amu757 No, not removed.
Tried to install both directly and by `vsix` file, in both cases got:
> Unable to install extension 'extension_id' as it is not compatible with VS Code '1.60.0'.

**Comment by rscwn** [comment]
Yea I get the same issue too, fixed it by installing with VSIX, it worked but only sometimes. 

> Still happy with it.

**Comment by erenmete** [comment]
latest vscode is incompatible with those extension and many more. old versions of vheditor come with older versions of vscode so they support the extensions, but termux apt install system is broken with the so its quite the conundrum
